# Generated by Django 5.2.2 on 2025-06-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0006_alter_customuser_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="profile_pic",
            field=models.ImageField(upload_to="profile_pics/"),
        ),
    ]
