# Generated by Django 5.2.2 on 2025-06-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0007_alter_students_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="profile_pic",
            field=models.FileField(upload_to="profile_pics/"),
        ),
    ]
