# Generated by Django 5.2.2 on 2025-06-07 07:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0009_alter_students_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="profile_pic",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
